In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)         #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)

    ########### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################################
    
#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

    ####### PARAMETRIZACION AUTOMATICA ###############################
    
    rango = 44
    NB = 4
    roundMode = 'round'
    saturateMode = 'saturate'
    
    ##################################################################
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(rango, premult_A, postmult_B, NB, roundMode, saturateMode)

    print('premult_A_stream:\n',premult_A_stream)
    print('postmult_B_stream:\n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  4

 Numero de multiplicaciones matriciales:  3


B_aux[m] en m = :  0

 [11. 12. 13. 14.]
B_aux[m] en m = :  1

 [21. 22. 23. 24.]
B_aux[m] en m = :  2

 [31. 32. 33. 34.]
B_aux[m] en m = :  3

 [41. 42. 43. 44.]
len(A_aux) 4
len(A_aux[0]) 4
A_aux 
 [[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]
 [41. 42. 43. 44.]]
len(B_aux) 4
len(B_aux[0]) 4
B_aux 
 [[44. 43. 42. 41.]
 [34. 33. 32. 31.]
 [24. 23. 22. 21.]
 [14. 13. 12. 11.]]
B_aux[m] en m = :  0

 [-11. -12. -13. -14.]
B_aux[m] en m = :  1

 [-21. -22. -23. -24.]
B_aux[m] en m = :  2

 [-31. -32. -33. -34.]
B_aux[m] en m = :  3

 [-41. -42. -43. -44.]
len(A_aux) 4
len(A_aux[0]) 4
A_aux 
 [[-11. -12. -13. -14.]
 [-21. -22. -23. -24.]
 [-31. -32. -33. -34.]
 [-41. -42. -43. -44.]]
len(B_aux) 4
len(B_aux[0]) 4
B_aux 
 [[-44. -43. -42. -41.]
 [-34. -33. -32. -31.]
 [-24. -23. -22. -21.]
 [-14. -13. -12. -11.]]
B_aux[m] en m = :  0

 [11. 12. 13. 14.]
B_aux[m] en m = :  1

 [21. 22. 23. 24.]
B_aux[m] en m = :  2

 [31. 32. 33. 34.]
B_aux[m] en m = :  3

 [41. 42. 43. 44.]
len(