In [1]:
#prueba1
import numpy as np
import SystolicMult as sysmult
import GeneralSystolicMult as gensysmult

N=4
M=4

A = np.array([[1,1,1,1],      # quizas se puede reemplazar con: np.ones(4,4, dtype = int)
              [1,1,1,1],
              [1,1,1,1],
              [1,1,1,1]])

b=np.array ([1,1,1,1])
c=np.array ([1,1,1,1])
d=np.array ([1,1,1,1])
e=np.array ([1,1,1,1])
print(b,c,d,e)
print("\n --------------------------------------- \n")

##prueba para agregar los ceros 
for i in range(3):
    b=np.insert(b,0,0)
    c=np.insert(c,0,0)
    d=np.insert(d,0,0)
    e=np.insert(e,0,0)
print("\nfilled matrix A")
print(b)
print(c)
print(d)
print(e)
print("\n --------------------------------------- \n")

#prueba para el roll acomodando la matriz
b=np.roll(b,0)
c=np.roll(c,-1)
d=np.roll(d,-2)
e=np.roll(e,-3)

print("\nshifted matrix A")
print(b)
print(c)
print(d)
print(e)

print("\n --------------------------------------- \n")
#matriz b prueba
b1=np.array ([11,1,1,1])
b2=np.array ([1,1,1,1])
b3=np.array ([1,1,1,1])
b4=np.array ([1,1,1,22])
print(b1,b2,b3,b4)

for i in range(3):
    b1=np.insert(b1,0,0)
    b2=np.insert(b2,0,0)
    b3=np.insert(b3,0,0)
    b4=np.insert(b4,0,0)
print("\nfilled matrix B")
print(b1)
print(b2)
print(b3)
print(b4)
print("\n --------------------------------------- \n")


b1=np.roll(b1,0)
b2=np.roll(b2,-1)
b3=np.roll(b3,-2)
b4=np.roll(b4,-3)

print("\nshifted matrix B")
print(b1)
print(b2)
print(b3)
print(b4)
print("\n --------------------------------------- \n")

B=np.append([b1],[b2],axis=0)
V=np.append([b3],[b4],axis=0)
bbb=np.append(B,V,axis=0)

print(bbb)

##rotacion de la matriz B
bbb=np.rot90(bbb,45)
print("\n --------------------------------------- \n")

print("fdd")
print(bbb)




[1 1 1 1] [1 1 1 1] [1 1 1 1] [1 1 1 1]

 --------------------------------------- 


filled matrix A
[0 0 0 1 1 1 1]
[0 0 0 1 1 1 1]
[0 0 0 1 1 1 1]
[0 0 0 1 1 1 1]

 --------------------------------------- 


shifted matrix A
[0 0 0 1 1 1 1]
[0 0 1 1 1 1 0]
[0 1 1 1 1 0 0]
[1 1 1 1 0 0 0]

 --------------------------------------- 

[11  1  1  1] [1 1 1 1] [1 1 1 1] [ 1  1  1 22]

filled matrix B
[ 0  0  0 11  1  1  1]
[0 0 0 1 1 1 1]
[0 0 0 1 1 1 1]
[ 0  0  0  1  1  1 22]

 --------------------------------------- 


shifted matrix B
[ 0  0  0 11  1  1  1]
[0 0 1 1 1 1 0]
[0 1 1 1 1 0 0]
[ 1  1  1 22  0  0  0]

 --------------------------------------- 

[[ 0  0  0 11  1  1  1]
 [ 0  0  1  1  1  1  0]
 [ 0  1  1  1  1  0  0]
 [ 1  1  1 22  0  0  0]]

 --------------------------------------- 

fdd
[[ 1  0  0  0]
 [ 1  1  0  0]
 [ 1  1  1  0]
 [11  1  1 22]
 [ 0  1  1  1]
 [ 0  0  1  1]
 [ 0  0  0  1]]


In [2]:
#prueba 2
a = np.array([[1, 2], [3, 4]])
print(a)
a_2 = np.insert(a,0,[8,5])
print('a_2',a_2)
v=a_2.transpose()     
print(v)

[[1 2]
 [3 4]]
a_2 [8 5 1 2 3 4]
[8 5 1 2 3 4]


In [3]:
#prueba3
import numpy as np

A=np.array([[0,0,1,1,1],
            [0,1,1,1,0],
            [1,1,1,0,0]])

B=np.array([[0,0,1],
            [0,1,1],
            [1,1,1],
            [1,1,0],
            [1,0,0]])

R=np.array([[1,1,1],
            [1,1,1],
            [1,1,1]])

##Processor
def P(a,b,c):
    p=a*b
    c=c+p
    return(c)
    ##return(c,a,b) #deberia tirar a y b para "conectar" con los demas 

jh=P(A[1,1],B[1,1],0)

print(jh)

for i in range(3):
    for j in range(5):
        R[i][i]=P(A[i][j],B[j][i],0)
        
print(R)


1
[[1 1 1]
 [1 0 1]
 [1 1 0]]


# Pruebas Santi


In [4]:
"""
  Formas utiles de trabajar:

    Crear una matriz 4*4 de ceros:
    a = np.zeros((4, 4), dtype=int)

    Insertar una columna de '1' en la posicion 0 de la matriz:
    a = np.insert(a, 0,np.ones((1,4), dtype=int), axis=1)

    Indexar un arreglo:
    a = A[0,:]  # Accedo a la primer fila de A
    a = A[:,0]  # Accedp a la primer col. de A

    Transponer un vector:
    a = a.T = a.transpose()

    Espejar una matriz (espeja por filas, con axis=1 espeja por columnas):
    A = np.flip()

"""

# Dimensiones de las matrices

N = 4   # Filas
M = 4   # Col.

# Matrices de entrada
A = np.ones((N,M), dtype=int)
B = np.ones((N,M), dtype=int)

# Matrices de salida
A1 = np.zeros((N, 2*M-1), dtype=int)
B1 = np.zeros((2*N-1, M), dtype=int)

print('Las matrices de entrada son:')
print('A:\n', A,'\nB:\n', B, '\n\n')

for i in range(N):
    a = A[i,:]                                  # Obtengo la primer fila
    a = np.insert(a, 0, np.zeros(M-1-i))        # Le inserto los ceros adelante   
    a = np.insert(a, 2*M-1-i, np.zeros(i))      # Le inserto los ceros atras 
    A1[i,:] = a                                 # Guardo en la matriz de salida

    b = B[:,i]                                  # Obtengo la primer col.
    b = b.T                                     # La transpongo para trabajarla como vector y le hago las mismas operaciones que a A
    b = np.insert(b, 0, np.zeros(N-1-i))          
    b = np.insert(b, 2*N-1-i, np.zeros(i))     
    b = b.T                                     # La vuelvo a transponer para guardarla en la matriz de salida
    B1[:,i] = b

print('Las matrices de salida son:')
print('A1:\n', A1, '\nB1:\n', B1)
print()

# Se rellenan las matrices dan vuelta para multiplicar mas facilmente los vectores

A1 = np.insert(A1, 0, np.zeros((N,M)), axis=1)
#print('La matriz A ampliada es:')
#print('A1:\n', A1)
#print()

B1 = np.insert(B1, 0, np.zeros((N,M)), axis=0)
#print('La matriz B ampliada es:')
#print('B1:\n', B1)
#print()

print("\nmatriz A1 dada vuelta en columnas:\n")
print(np.flip(A1, axis=1))
print()

#print("\nmatriz B1 transpuesta:\n")
#print(B1.T)
#print()

print("\nmatriz B1 transpuesta dada vuelta en columnas:\n")
print(np.flip(B1.T, axis=1))
print()

A1 = np.flip(A1, axis=1)
B1 = np.flip(B1.T, axis=1)


#sysmult.SystolicMult(A1,B1)

gensysmult.GeneralSystolicMult(A1,B1)

Las matrices de entrada son:
A:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 
B:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 


Las matrices de salida son:
A1:
 [[0 0 0 1 1 1 1]
 [0 0 1 1 1 1 0]
 [0 1 1 1 1 0 0]
 [1 1 1 1 0 0 0]] 
B1:
 [[0 0 0 1]
 [0 0 1 1]
 [0 1 1 1]
 [1 1 1 1]
 [1 1 1 0]
 [1 1 0 0]
 [1 0 0 0]]


matriz A1 dada vuelta en columnas:

[[1 1 1 1 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0 0]]


matriz B1 transpuesta dada vuelta en columnas:

[[1 1 1 1 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0 0]]


 i =  0 

C_w :
 [[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 i =  1 

C_w :
 [[2 1 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 i =  2 

C_w :
 [[3 2 1 0]
 [2 1 0 0]
 [1 0 0 0]
 [0 0 0 0]]

 i =  3 

C_w :
 [[4 3 2 1]
 [3 2 1 0]
 [2 1 0 0]
 [1 0 0 0]]

 i =  4 

C_w :
 [[4 4 3 2]
 [4 3 2 1]
 [3 2 1 0]
 [2 1 0 0]]

 i =  5 

C_w :
 [[4 4 4 3]
 [4 4 3 2]
 [4 3 2 1]
 [3 2 1 0]]

 i =  6 

C_w