In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult

In [2]:
# Dimensiones de las matrices

N = 4   # Filas
M = 4   # Col.

# Matrices de entrada

A = np.ones((N,M), dtype=int)
B = np.ones((N,M), dtype=int)
C = 10*A
print(C)
D = C

premult_A = np.ones((N,2*M), dtype=int)
postmult_B = np.ones((2*N,M), dtype=int)

for i in range(N):
    print(i)
    print(A[i])
    A_aux = A[i,:]
    B_aux = B[i,:]
    A_aux = np.insert(A_aux,0,C[i])
    B_aux = np.insert(B_aux,0,D[i])
    
    premult_A[i,:] = A_aux
    postmult_B[:,i] = B_aux

print('premult_A',premult_A)
print('postmult_B: ',postmult_B)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
0
[1 1 1 1]
1
[1 1 1 1]
2
[1 1 1 1]
3
[1 1 1 1]
premult_A [[10 10 10 10  1  1  1  1]
 [10 10 10 10  1  1  1  1]
 [10 10 10 10  1  1  1  1]
 [10 10 10 10  1  1  1  1]]
postmult_B:  [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]]


In [3]:
[A1,B1] = inputgen.InputGenerator(premult_A,postmult_B)

print('premult_A_stream:\n',A1)
print('postmult_B_stream:\n',B1)

countsysmult.CounterGenSysMult(A1,B1)

N_matrix_mult:  2

matriz A1 dada vuelta en columnas:

[[ 1  1  1  1 10 10 10 10  0  0  0  0  0  0  0]
 [ 0  1  1  1  1 10 10 10 10  0  0  0  0  0  0]
 [ 0  0  1  1  1  1 10 10 10 10  0  0  0  0  0]
 [ 0  0  0  1  1  1  1 10 10 10 10  0  0  0  0]]


matriz B1 transpuesta dada vuelta en columnas:

[[ 1  1  1  1 10 10 10 10  0  0  0  0  0  0  0]
 [ 0  1  1  1  1 10 10 10 10  0  0  0  0  0  0]
 [ 0  0  1  1  1  1 10 10 10 10  0  0  0  0  0]
 [ 0  0  0  1  1  1  1 10 10 10 10  0  0  0  0]]

premult_A_stream:
 [[ 1  1  1  1 10 10 10 10  0  0  0  0  0  0  0]
 [ 0  1  1  1  1 10 10 10 10  0  0  0  0  0  0]
 [ 0  0  1  1  1  1 10 10 10 10  0  0  0  0  0]
 [ 0  0  0  1  1  1  1 10 10 10 10  0  0  0  0]]
postmult_B_stream:
 [[ 1  1  1  1 10 10 10 10  0  0  0  0  0  0  0]
 [ 0  1  1  1  1 10 10 10 10  0  0  0  0  0  0]
 [ 0  0  1  1  1  1 10 10 10 10  0  0  0  0  0]
 [ 0  0  0  1  1  1  1 10 10 10 10  0  0  0  0]]

 i =  0 

[False, False, False, False, False, False, False]
C_w :
 [[1 0 0 0]
 [0 