In [1]:
import numpy as np
import math
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    import math

############### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################
    
    ########## ENTRADAS  ############
    N = int(input('\n DIMENSIONES DEL ARREGLO SISTOLICO : ')) # Filas
    N_matrix_mult = int(input('\n NUMERO DE MULTIPLICACIONES MATRICIALES : ')) 

#    Input_Data_Type = int(input('Ingrese 'float' o 'fixed' segun el tipo de dato que desea en las entradas: '))
#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    NB_F = int(input('Ingrese número de bits fraccionales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

    ########### SALIDAS   ###########

#    NB_OUT = int(input('Ingrese número de bits totales: '))


########### PARAMETRIZACION AUTOMATICA ###############
    
    ########## ENTRADAS  ############
#    N = 4
#    N_matrix_mult = 10
    
    Input_Data_Type = 'fixed'
    rango = 255
    NB = 8
    NB_F = 7
    roundMode = 'round'
    saturateMode = 'saturate'
    
    latencia = N
    
    ########### SALIDAS   ###########
    
#    NB_OUT = 10
#    NB_OUT_F = int(NB_OUT - 2 - math.ceil(math.log2(N))) 
    
    # CASO FULL RESOLUTION
    
    NB_OUT = NB * 2 + math.ceil(math.log2(N))
    NB_OUT_F = NB_F * 2
    
    
    print('\n NB_OUT :    ',NB_OUT)
    print('\n NB_OUT_F :  ',NB_OUT_F)
    
######################################################################
######## COMIENZA CONCATENACION DE FUNCIONES #########################
######################################################################

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)  #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(Input_Data_Type,rango, premult_A, postmult_B, NB, NB_F, roundMode, saturateMode)

    print('premult_A_stream: \n',premult_A_stream)
    print('postmult_B_stream: \n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream,latencia,rango,NB_OUT,NB_OUT_F)
    
PlataformaVerificacion()


 DIMENSIONES DEL ARREGLO SISTOLICO :  16

 NUMERO DE MULTIPLICACIONES MATRICIALES :  10



 NB_OUT :     20

 NB_OUT_F :   14
B_aux[m] en m = :  0

 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26.]
B_aux[m] en m = :  1

 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]
B_aux[m] en m = :  2

 [31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46.]
B_aux[m] en m = :  3

 [41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56.]
B_aux[m] en m = :  4

 [51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66.]
B_aux[m] en m = :  5

 [61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74. 75. 76.]
B_aux[m] en m = :  6

 [71. 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86.]
B_aux[m] en m = :  7

 [81. 82. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96.]
B_aux[m] en m = :  8

 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103. 104.
 105. 106.]
B_aux[m] en m = :  9

 [101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114.
 115. 116.]
B_aux[m] en m = :  10

 [111. 112. 113. 