In [1]:
import numpy as np
import math
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)         #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)

############### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################################
    
#    print('PARAMETRIZACION MANUAL DE LAS ENTRADAS :')

#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    NB_F = int(input('Ingrese número de bits fraccionales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

#    print('PARAMETRIZACION MANUAL DE LAS salidas :')

#    NB_OUT = int(input('Ingrese número de bits totales: '))


########### PARAMETRIZACION AUTOMATICA ###############################
    
    # PARAMETRIZACION AUTOMATICA DE LAS ENTRADAS
    rango = 255
    NB = 8
    NB_F = 7
    roundMode = 'round'
    saturateMode = 'saturate'
    
    # PARAMETRIZACION AUTOMATICA DE LAS SALIDAS
    
    NB_OUT = 14
    
######################################################################
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(rango, premult_A, postmult_B, NB, NB_F, roundMode, saturateMode)

    print('premult_A_stream:\n',premult_A_stream)
    print('postmult_B_stream:\n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream,NB_OUT)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  6

 Numero de multiplicaciones matriciales:  5


B_aux[m] en m = :  0

 [11. 12. 13. 14. 15. 16.]
B_aux[m] en m = :  1

 [21. 22. 23. 24. 25. 26.]
B_aux[m] en m = :  2

 [31. 32. 33. 34. 35. 36.]
B_aux[m] en m = :  3

 [41. 42. 43. 44. 45. 46.]
B_aux[m] en m = :  4

 [51. 52. 53. 54. 55. 56.]
B_aux[m] en m = :  5

 [61. 62. 63. 64. 65. 66.]
len(A_aux) 6
len(A_aux[0]) 6
A_aux 
 [[11. 12. 13. 14. 15. 16.]
 [21. 22. 23. 24. 25. 26.]
 [31. 32. 33. 34. 35. 36.]
 [41. 42. 43. 44. 45. 46.]
 [51. 52. 53. 54. 55. 56.]
 [61. 62. 63. 64. 65. 66.]]
len(B_aux) 6
len(B_aux[0]) 6
B_aux 
 [[66. 65. 64. 63. 62. 61.]
 [56. 55. 54. 53. 52. 51.]
 [46. 45. 44. 43. 42. 41.]
 [36. 35. 34. 33. 32. 31.]
 [26. 25. 24. 23. 22. 21.]
 [16. 15. 14. 13. 12. 11.]]
B_aux[m] en m = :  0

 [-11. -12. -13. -14. -15. -16.]
B_aux[m] en m = :  1

 [-21. -22. -23. -24. -25. -26.]
B_aux[m] en m = :  2

 [-31. -32. -33. -34. -35. -36.]
B_aux[m] en m = :  3

 [-41. -42. -43. -44. -45. -46.]
B_aux[m] en m = :  4

 [-51. -52. -53. -54. -55. -56.]
B_aux[m] en m = :  5

 [-61. -6