In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [ ]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)         #Genera las NMtx solicitadas y las concatena para
#    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)

    rango = int(input('Ingrese valor absoluto del mínimo negativo posible de los coeficientes: '))
    NB = int(input('Ingrese número de bits totales: '))
    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
    roundMode = input("roundMode >> ")
    saturateMode = input("saturateMode >> ")
    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [A1,B1] = inputgen.InputGenerator(premult_A,postmult_B)

    print('premult_A_stream:\n',A1)
    print('postmult_B_stream:\n',B1)
    
#    countsysmult.CounterGenSysMult(A1,B1)
    countsysmult2.CounterGenSysMult2(A1,B1)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  5

 Numero de multiplicaciones matriciales:  5


len(premult_A) =  5
len(premult_A) =  25

 premult_A : 

[5. 5. 5. 0. 0. 4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1.]
[5. 5. 5. 0. 0. 4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1.]
[5. 5. 5. 0. 0. 4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1.]
len(postmult_B) =  25
len(postmult_B) =  5

 postmult_B: 

[5. 5. 5. 5. 0.]
[5. 5. 5. 5. 0.]
[5. 5. 5. 5. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[4. 4. 4. 4. 0.]
[4. 4. 4. 4. 0.]
[4. 4. 4. 4. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
