In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult

In [2]:
def AutoMatrixGenerator(N,N_matrix_mult):

    premult_A = []
    postmult_B = []
    
    A_aux = np.zeros((N,N), dtype=float)
    B_aux = np.zeros((N,N), dtype=float)

    for k in range(N):
        premult_A.append([])

    for j in range(N_matrix_mult):

        A = np.ones((N,N), dtype = float)
        B = np.ones((N,N), dtype = float)

#        if (j%2 == 0 and  1 < j < 5):  # Genera matrices no cuadradas de resultado no cuadrado
#            A = np.ones((N-2,N), dtype = float)
#            B = np.ones((N,N-1), dtype = float)
#
#        elif (j%2 == 1 and 3 < j < 6):   # Genera matrices cuadradas de dimension menor que la total
#            A = np.ones((N-2,N-2), dtype = float)
#            B = np.ones((N-2,N-2), dtype = float)
        
 # COMENTAR PARA GENERAR TODAS MATRICES COMPLETAS CON UNOS
        A = A*(1+1*j)
        B = B*(1+1*j)

#        print('\n j = ',j, '\n')
#        print('len(A)',len(A))
#        print('A \n',A)
#        print('len(B)',len(B))
#        print('B \n',B)
#        
#        if (len(A[0]) != len(B)): # VERIFICA QUE SEA POSIBLE MULTIPLICAR
#            print('Las matrices con estas dimensiones no se pueden multiplicar. Comience nuevamente. \n')
#            PlataformaVerificacion()
            
#            print('LEN A[O] : ', len(A[0]))
#            print(' \n LEN A : ', len(A), '\n')


#        if(len(A[0]) < N):  # Agrega columnas de ceros en caso de ser de menor dimension
#            for l in range(len(A)):
#                A_aux[l,:] = np.append(A[l,:],np.zeros(N-len(A[l]), dtype = float))
#        else:
#            for l in range(len(A)):
#                A_aux[l,:] = A[l,:]
#                
#        if(len(A) < N):    # Agrega filas de ceros en caso de ser de menor dimension
#            for m in range(N):
#                    A_aux[:,m] = np.append(A[:,m],np.zeros(N-len(A),dtype = float))
#                    
#        if(len(B[0]) < N):  # Agrega columnas de ceros en caso de ser de menor dimension
#            for p in range(len(B)):
#                B_aux[p,:] = np.append(B[p,:],np.zeros(N-len(B[p]), dtype = float))
#        else:
#            for p in range(len(B)):
#                B_aux[p,:] = B[p,:]
#                
#        if(len(B) < N):    # Agrega filas de ceros en caso de ser de menor dimension
#            for q in range(N):
#                    B_aux[:,q] = np.append(B[:,q],np.zeros(N-len(A),dtype = float))
                
                
#        print('len(A_aux)',len(A_aux))
#        print('A_aux \n',A_aux)
#        print('len(B_aux)',len(B_aux))
#        print('B_aux \n',B_aux)
                
        for i in range(N):  # Adjunta las matrices en formato cascada
            premult_A[i] = np.insert(premult_A[i],0,A[i,:])
            postmult_B.append(B[i,:])

    premult_A = np.asarray(premult_A) #Se prepara el formato para ingreso a la funcion InputGenerator()
    postmult_B = np.asarray(postmult_B)

    postmult_B = np.flip(postmult_B)

    print('premult_A',premult_A)
    print('len(premult_A)',len(premult_A))
    print('postmult_B: ',postmult_B)
    print('len(postmult_B)',len(postmult_B))
    
    return (premult_A,postmult_B)  #Las salidas son entrada de la funcion InputGenerator()
    

In [3]:
def InputGenerator(premult_A,postmult_B):
    
    import numpy as np
    
    N = len(premult_A)
    M = N
    
    N_matrix_mult = len(postmult_B)//len(premult_A)
    print('N_matrix_mult: ',N_matrix_mult)
    
    premult_A_stream   = np.zeros((N, (N_matrix_mult*M + M -1)), dtype=float)
    postmult_B_stream  = np.zeros(((N_matrix_mult*N + N -1, M)), dtype=float)
    
    
    for i in range(N):
        print('premult_A[i,:]',premult_A[i,:])
        a = premult_A[i,:]                                  # Obtengo la primer fila
        print('a = ',a)
        a = np.insert(a, 0, np.zeros(M-1-i))        # Le inserto los ceros adelante   
        a = np.insert(a, N_matrix_mult*M + M-1-i, np.zeros(i))      # Le inserto los ceros atras 
        premult_A_stream[i,:] = a                                 # Guardo en la matriz de salida

        b = postmult_B[:,i]                                  # Obtengo la primer col.
        b = b.T                                     # La transpongo para trabajarla como vector y le hago las mismas operaciones que a A
        b = np.insert(b, 0, np.zeros(N-1-i))          
        b = np.insert(b, N_matrix_mult*N + N-1-i, np.zeros(i))     
        b = b.T                                     # La vuelvo a transponer para guardarla en la matriz de salida
        postmult_B_stream[:,i] = b
        
        print('\n i = ',i, '\n')
        print('premult_A_stream \n ',premult_A_stream)
        print('len(premult_A_stream \n)',len(premult_A_stream))
#        print('postmult_B_stream: ',postmult_B_stream)
#        print('len(postmult_B_stream)',len(postmult_B_stream))
    
    premult_A_stream = np.insert(premult_A_stream, 0, np.zeros((N,M)), axis=1)
    postmult_B_stream = np.insert(postmult_B_stream, 0, np.zeros((N,M)), axis=0)
    
    print("\nmatriz A1 dada vuelta en columnas:\n")
    print(np.flip(premult_A_stream, axis=1))
    print()

    #print("\nmatriz B1 transpuesta:\n")
    #print(B1.T)
    #print()

    print("\nmatriz B1 transpuesta dada vuelta en columnas:\n")
    print(np.flip(postmult_B_stream.T, axis=1))
    print()

    premult_A_stream = np.flip(premult_A_stream, axis=1)
    postmult_B_stream = np.flip(postmult_B_stream.T, axis=1)
    
    return(premult_A_stream,postmult_B_stream)

In [4]:
def PlataformaVerificacion():
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    N = int(input('Numero de filas = Numero de columnas : ')) # Filas
    
    # Numero de multiplicaciones matriciales : 
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: '))   # Col.

    [premult_A,postmult_B] = AutoMatrixGenerator(N,N_matrix_mult)
    
    #[A1,B1] = inputgen.InputGenerator(premult_A,postmult_B)
    
    [A1,B1] = InputGenerator(premult_A,postmult_B)

    print('premult_A_stream:\n',A1)
    print('postmult_B_stream:\n',B1)
    
    countsysmult.CounterGenSysMult(A1,B1)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas :  4

 Numero de multiplicaciones matriciales:  6


premult_A [[6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
 [6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
 [6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
 [6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]]
len(premult_A) 4
postmult_B:  [[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
len(postmult_B) 24
N_matrix_mult:  6
premult_A[i,:] [6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
a =  [6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]

 i =  0 

premult_A_stream 
  [[0. 0. 0. 6. 6. 6. 6. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 