In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult

In [2]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)
    
    [A1,B1] = inputgen.InputGenerator(premult_A,postmult_B)

    print('premult_A_stream:\n',A1)
    print('postmult_B_stream:\n',B1)
    
    countsysmult.CounterGenSysMult(A1,B1)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  4

 Numero de multiplicaciones matriciales:  5


len(premult_A) =  4

 premult_A 
 [[5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
 [5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3. 3. 2. 2. 2. 2. 1. 1. 1. 1.]
 [0. 0. 0. 0. 4. 4. 4. 4. 0. 0. 0. 0. 2. 2. 2. 2. 1. 1. 1. 1.]
 [0. 0. 0. 0. 4. 4. 4. 4. 0. 0. 0. 0. 2. 2. 2. 2. 1. 1. 1. 1.]]
len(postmult_B) =  20

 postmult_B: 
 [[5. 5. 5. 0.]
 [5. 5. 5. 0.]
 [5. 5. 5. 0.]
 [5. 5. 5. 0.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [3. 3. 3. 0.]
 [3. 3. 3. 0.]
 [3. 3. 3. 0.]
 [3. 3. 3. 0.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
N_matrix_mult:  5

matriz A1 dada vuelta en columnas:

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 0 0 0 0 0 0 0]
 [0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 0 0 0 0 0 0]
 [0 0 1 1 1 1 2 2 2 2 0 0 0 0 4 4 4 4 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 2 2 2 2 0 0 0 0 4 4 4 4 0 0 0 0 0 0 0 0]]


matriz B1 transpuesta dada vuelta en columnas:

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 