In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)         #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)

    ########### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################################
    
#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

    ####### PARAMETRIZACION AUTOMATICA ###############################
    
    rango = 255
    NB = 8
    roundMode = 'round'
    saturateMode = 'saturate'
    
    ##################################################################
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(rango, premult_A, postmult_B, NB, roundMode, saturateMode)

    print('premult_A_stream:\n',premult_A_stream)
    print('postmult_B_stream:\n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  8

 Numero de multiplicaciones matriciales:  2


B_aux[m] en m = :  0

 [11. 12. 13. 14. 15. 16. 17. 18.]
B_aux[m] en m = :  1

 [21. 22. 23. 24. 25. 26. 27. 28.]
B_aux[m] en m = :  2

 [31. 32. 33. 34. 35. 36. 37. 38.]
B_aux[m] en m = :  3

 [41. 42. 43. 44. 45. 46. 47. 48.]
B_aux[m] en m = :  4

 [51. 52. 53. 54. 55. 56. 57. 58.]
B_aux[m] en m = :  5

 [61. 62. 63. 64. 65. 66. 67. 68.]
B_aux[m] en m = :  6

 [71. 72. 73. 74. 75. 76. 77. 78.]
B_aux[m] en m = :  7

 [81. 82. 83. 84. 85. 86. 87. 88.]
len(A_aux) 8
len(A_aux[0]) 8
A_aux 
 [[11. 12. 13. 14. 15. 16. 17. 18.]
 [21. 22. 23. 24. 25. 26. 27. 28.]
 [31. 32. 33. 34. 35. 36. 37. 38.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [51. 52. 53. 54. 55. 56. 57. 58.]
 [61. 62. 63. 64. 65. 66. 67. 68.]
 [71. 72. 73. 74. 75. 76. 77. 78.]
 [81. 82. 83. 84. 85. 86. 87. 88.]]
len(B_aux) 8
len(B_aux[0]) 8
B_aux 
 [[88. 87. 86. 85. 84. 83. 82. 81.]
 [78. 77. 76. 75. 74. 73. 72. 71.]
 [68. 67. 66. 65. 64. 63. 62. 61.]
 [58. 57. 56. 55. 54. 53. 52. 51.]
 [48. 47. 46. 45. 44. 43. 42. 41.]
 [38. 37. 36. 