In [1]:
import numpy as np
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult

import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2

In [2]:
def PlataformaVerificacion():
    
    print('\n Dimensiones del arreglo sistolico para multiplicacion matricial: ')
    
    N = int(input('Numero de filas = Numero de columnas = ')) # Filas
    
    N_matrix_mult = int(input('\n Numero de multiplicaciones matriciales: ')) 

    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)
    
    [A1,B1] = inputgen.InputGenerator(premult_A,postmult_B)

    print('premult_A_stream:\n',A1)
    print('postmult_B_stream:\n',B1)
    
#    countsysmult.CounterGenSysMult(A1,B1)
    countsysmult2.CounterGenSysMult2(A1,B1)
    
PlataformaVerificacion()


 Dimensiones del arreglo sistolico para multiplicacion matricial: 


Numero de filas = Numero de columnas =  5

 Numero de multiplicaciones matriciales:  4


len(premult_A) =  5
len(premult_A) =  20

 premult_A : 

[4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.]
[4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.]
[4. 4. 4. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1.]
len(postmult_B) =  20
len(postmult_B) =  5

 postmult_B: 

[4. 4. 4. 4. 0.]
[4. 4. 4. 4. 0.]
[4. 4. 4. 4. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
N_matrix_mult:  4
premult_A_stream:
 [[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 0 0 4 4 4 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 0 0 4 4 4 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 0 0 4 4 4 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 