In [1]:
import numpy as np
import math
#import SystolicMult as sysmult
#import GeneralSystolicMult as gensysmult
import AutoMatrixGenerator as automatgen
import CoefInputMatrixGenerator as coinmatgen
import RandomMTX_Gen as ranmatgen
import InputGenerator as inputgen
import CounterGenSysMult as countsysmult
import CounterGenSysMult_V2 as countsysmult2
import NormalizedFixed_Matrix as normMtx
import _fixedInt as fInt

In [2]:
def PlataformaVerificacion():
    
    import math

############### PARAMETROS DE CUANTIZACION ###########################

    ####### PARAMETRIZACION MANUAL ###################
    
    ########## ENTRADAS  ############
#    N = int(input('\n DIMENSIONES DEL ARREGLO SISTOLICO : ')) # Filas
#    N_matrix_mult = int(input('\n NUMERO DE MULTIPLICACIONES MATRICIALES : ')) 

#    Input_Data_Type = int(input('Ingrese 'float' o 'fixed' segun el tipo de dato que desea en las entradas: '))
#    rango = int(input('Ingrese el rango de normalizacion: '))
#    NB = int(input('Ingrese número de bits totales: '))
#    NB_F = int(input('Ingrese número de bits fraccionales: '))
#    print("Indique si se utilizará redondeo(round) o truncamiento(trunc) y el modo de saturación(saturate/overflow)")
#    roundMode = input("roundMode >> ")
#    saturateMode = input("saturateMode >> ")

    ########### SALIDAS   ###########

#    NB_OUT = int(input('Ingrese número de bits totales: '))


########### PARAMETRIZACION AUTOMATICA ###############
    
    ########## ENTRADAS  ############
    N = 32
    N_matrix_mult = 10
    
    Input_Data_Type = 'fixed'
    rango = 255
    NB = 8
    NB_F = 7
    roundMode = 'round'
    saturateMode = 'saturate'
    
    latencia = N
    
    ########### SALIDAS   ###########
    
    NB_OUT_LIM = 16
    NB_OUT_F_LIM = int(NB_OUT_LIM - 2 - math.ceil(math.log2(N))) 
    
    # CASO FULL RESOLUTION
    
    NB_OUT_FULL = NB * 2 + math.ceil(math.log2(N))
    NB_OUT_F_FULL = NB_F * 2
    
    
    print('\n NB_OUT_LIM :    ',NB_OUT_LIM)
    print('\n NB_OUT_F_LIM :  ',NB_OUT_F_LIM)
    print('\n NB_OUT_FULL :    ',NB_OUT_FULL)
    print('\n NB_OUT_F_FULL :  ',NB_OUT_F_FULL)
    
######################################################################
######## COMIENZA CONCATENACION DE FUNCIONES #########################
######################################################################

#    [premult_A,postmult_B] = automatgen.AutoMatrixGenerator(N,N_matrix_mult)  #Genera las NMtx solicitadas y las concatena para
    [premult_A,postmult_B] = coinmatgen.CoefInputMatrixGenerator(N,N_matrix_mult)
#    [premult_A,postmult_B] = ranmatgen.RandomMTX_Gen(N,N_matrix_mult)
    
#    [premult_A,postmult_B] = normMtx.NormalizedFixedMatrix(rango, premult_A, postmult_B, NB, roundMode, saturateMode)
    
    [premult_A_stream,postmult_B_stream] = inputgen.InputGenerator(Input_Data_Type,rango, premult_A, postmult_B, NB, NB_F, roundMode, saturateMode)

#    print('premult_A_stream: \n',premult_A_stream)
#    print('postmult_B_stream: \n',postmult_B_stream)
    
#    countsysmult.CounterGenSysMult(premult_A_stream,postmult_B_stream)
    countsysmult2.CounterGenSysMult2(premult_A_stream,postmult_B_stream,latencia,rango,NB_OUT_LIM,NB_OUT_F_LIM,NB_OUT_FULL,NB_OUT_F_FULL)
    
PlataformaVerificacion()



 NB_OUT_LIM :     16

 NB_OUT_F_LIM :   9

 NB_OUT_FULL :     21

 NB_OUT_F_FULL :   14
N_matrix_mult:  10
premult_A_stream:
 [[42. 41. 40. ...  0.  0.  0.]
 [ 0. 52. 51. ...  0.  0.  0.]
 [ 0.  0. 62. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
postmult_B_stream:
 [[321. 311. 301. ...   0.   0.   0.]
 [  0. 322. 312. ...   0.   0.   0.]
 [  0.   0. 323. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
LONGITUD DE A :  32
N_Matrix_Mult =  10

 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 ROUNDED: C_w_bits 0101111101101010 


 R

KeyboardInterrupt: 