In [1]:
"""
  Formas utiles de trabajar:

    Crear una matriz 4*4 de ceros:
    a = np.zeros((4, 4), dtype=int)

    Insertar una columna de '1' en la posicion 0 de la matriz:
    a = np.insert(a, 0,np.ones((1,4), dtype=int), axis=1)

    Indexar un arreglo:
    a = A[0,:]  # Accedo a la primer fila de A
    a = A[:,0]  # Accedp a la primer col. de A

    Transponer un vector:
    a = a.T = a.transpose()

    Espejar una matriz (espeja por filas, con axis=1 espeja por columnas):
    A = np.flip()

"""
import numpy as np
# Dimensiones de las matrices

N = 4   # Filas
M = 4   # Col.

# Matrices de entrada
#A = np.ones((N,M), dtype=int)
#B = np.ones((N,M), dtype=int)

A = np.array([[1,2,3,4],
              [1,2,3,4],
              [1,2,3,4],
              [1,2,3,4]])


B = np.array([[1,2,3,4],
             [1,2,3,4],
             [1,2,3,4],
             [1,2,3,4]])

# B = np.array([[1,1,1,1],
#               [2,2,2,2],
#               [3,3,3,3],
#               [4,4,4,4]])

# B = np.array([[4,3,2,1],
#               [4,3,2,1],
#               [4,3,2,1],
#               [4,3,2,1]])


# Matrices de salida
A1 = np.zeros((N, 2*M-1), dtype=int)
B1 = np.zeros((2*N-1, M), dtype=int)

print('Las matrices de entrada son:')
print('A:\n', A,'\nB:\n', B, '\n\n')

for i in range(N):
  a = A[i,:]                                  # Obtengo la primer fila
  a = np.insert(a, 0, np.zeros(M-1-i))        # Le inserto los ceros adelante   
  a = np.insert(a, 2*M-1-i, np.zeros(i))      # Le inserto los ceros atras 
  A1[i,:] = a                                 # Guardo en la matriz de salida

  b = B[:,i]                                  # Obtengo la primer col.
  b = b.T                                     # La transpongo para trabajarla como vector y le hago las mismas operaciones que a A
  b = np.insert(b, 0, np.zeros(N-1-i))          
  b = np.insert(b, 2*N-1-i, np.zeros(i))     
  b = b.T                                     # La vuelvo a transponer para guardarla en la matriz de salida
  B1[:,i] = b

print('Las matrices de salida son:')
print('A1:\n', A1, '\nB1:\n', B1)
print()

# Se rellenan las matrices dan vuelta para multiplicar mas facilmente los vectores

A1 = np.insert(A1, 0, np.zeros((N,M)), axis=1)
print('La matriz A ampliada es:')
print('A1:\n', A1)
print()

B1 = np.insert(B1, 0, np.zeros((N,M)), axis=0)
print('La matriz B ampliada es:')
print('B1:\n', B1)
print()

print("\nmatriz A1 dada vuelta en columnas:\n")
print(np.flip(A1, axis=1))
print()

print("\nmatriz B1 transpuesta:\n")
print(B1.T)
print()

print("\nmatriz B1 transpuesta dada vuelta en columnas:\n")
print(np.flip(B1.T, axis=1))
print()

A1 = np.flip(A1, axis=1)
B1 = np.flip(B1.T, axis=1)

#sysmult.SystolicMult(A1,B1)}


Las matrices de entrada son:
A:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] 
B:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] 


Las matrices de salida son:
A1:
 [[0 0 0 1 2 3 4]
 [0 0 1 2 3 4 0]
 [0 1 2 3 4 0 0]
 [1 2 3 4 0 0 0]] 
B1:
 [[0 0 0 4]
 [0 0 3 4]
 [0 2 3 4]
 [1 2 3 4]
 [1 2 3 0]
 [1 2 0 0]
 [1 0 0 0]]

La matriz A ampliada es:
A1:
 [[0 0 0 0 0 0 0 1 2 3 4]
 [0 0 0 0 0 0 1 2 3 4 0]
 [0 0 0 0 0 1 2 3 4 0 0]
 [0 0 0 0 1 2 3 4 0 0 0]]

La matriz B ampliada es:
B1:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]
 [0 0 3 4]
 [0 2 3 4]
 [1 2 3 4]
 [1 2 3 0]
 [1 2 0 0]
 [1 0 0 0]]


matriz A1 dada vuelta en columnas:

[[4 3 2 1 0 0 0 0 0 0 0]
 [0 4 3 2 1 0 0 0 0 0 0]
 [0 0 4 3 2 1 0 0 0 0 0]
 [0 0 0 4 3 2 1 0 0 0 0]]


matriz B1 transpuesta:

[[0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 2 2 2 2 0]
 [0 0 0 0 0 3 3 3 3 0 0]
 [0 0 0 0 4 4 4 4 0 0 0]]


matriz B1 transpuesta dada vuelta en columnas:

[[1 1 1 1 0 0 0 0 0 0 0]
 [0 2 2 2 2 0 0 0 0 0 0]
 [0 0 3 3 3 3 0 0 0 0 0]
 [0 0 0

In [25]:

#!/usr/bin/env python
# coding: utf-8

# In[1]:

def GSM(A,B): # A Y B MATRICES

    import numpy as np
    
    def PE(a,b,c):   ## Define el comportamiento de una celda cualquiera con entradas a y b.
        p=a*b        ## (La entrada c es siempre el valor anterior)
        c=c+p
        return(a,b,c)  ## Devuelve a y b para usar como entrada a la siguiente celda
    
    n = len(A)  ## Numero de filas en matriz A o de columnas en matriz B.
    N_clocks = (3*n-1)  ## Ciclos necesarios para obtener el valor de la celda P44
    
    A_w = np.zeros((n,n), dtype=int)  ## Variables de conexion horizontal entre celdas
    B_w = np.zeros((n,n), dtype=int)  ## Variables de conexion vertical entre celdas
    C_w = np.zeros((n,n), dtype=int)  ## Variable de sobreescritura de valores, luego de N_clocks es salida del sistema
    
    [A_w_in,B_w_in,C_w_in] = [0,0,0]       ## Variables auxiliares para sobreescribir
    [A_w_out,B_w_out,C_w_out] = [0,0,0]
    
    
    file = open("C:/Procom/ocho/matching.txt", "w")
    
    for i in range(N_clocks):     # [0 , 1 , ... , n-1]
        
        print('\n bucle del i = ',i, '\n')        
        
        #res = ''.join(ele for sub in C_w for ele in sub) 
        res = str(C_w).replace('[','').replace(']','').replace('\n','')
        file.write(res+"\n")
        print(res)
        
        for j in range(n):  # Se trasladan variables de conexion con: [j=0,1 valor]   [j=1,3 valores] 
#                                                                     [j=2,5 valores] [j=3,7 valores] 
#            print(' bucle del j = ',j, '\n')  
#            print('C_w :\n',C_w,'\n')

            for m in range(j):   # Se trasladan variables de conexion solo de la matriz triangular superior
#                print('bucle del m = ',m, '\n') 
                if (j == (n-1)):
                    B_w_in = B[n-1-m][i]#Solo a la primera fila se le ingresan valores de la matriz de input B
#                    print("B_w_in = ",B_w_in)
                else:
                    B_w_in = B_w[n-2-j][n-1-m]
#                    print("B_w_in = ",B_w_in)

                    
                A_w_in = A_w[n-1-j][n-2-m]#Asignaciones cuando no se esta en la primera fila
#                print("A_w_in = ",A_w_in)
                C_w_in = C_w[n-1-j][n-1-m]
#                print("C_w_in = ",C_w_in)
                [A_w_out,B_w_out,C_w_out] = PE(A_w_in,B_w_in,C_w_in)  # Aca se ejecuta el PE y se hacen los traslados
#                print("m[A_w_out,B_w_out,C_w_out] = ",[A_w_out,B_w_out,C_w_out])
                A_w[n-1-j][n-1-m] = A_w_out
                B_w[n-1-j][n-1-m] = B_w_out
                C_w[n-1-j][n-1-m] = C_w_out
            
            for k in range(j+1): # Se trasladan variables de conexion de la diagonal y la matriz triangular inferior
                
                if (j == (n-1)):
 #                   print('bucle del k = ',k, '\n')  
                    A_w_in = A[n-1-k][i]  # Solo a la primera columna se le ingresan valores de la matriz de input A
#                    print(A_w_in)
                    if (k == (n-1)):
                        B_w_in = B[0][i]# Al elemento de la diagonal se le ingresa valor de la matriz de input B
#                        print("B_w_in = ",B_w_in)
                    else:
                        B_w_in = B_w[n-2-k][0]
#                        print("B_w_in = ",B_w_in)

                else:
                    A_w_in = A_w[n-2-k][n-1-j] #Asignaciones cuando no se esta en la primera columna
                    B_w_in = B_w[n-2-j][n-1-k]
#                    print(' k = ',k, '\n')  
#                    print('A_w_in :\n',A_w_in)
#                    print('B_w_in :\n',B_w_in)
                    
                C_w_in = C_w[n-1-k][n-1-j]
#                print("C_w_in = ",C_w_in)
                [A_w_out,B_w_out,C_w_out] = PE(A_w_in,B_w_in,C_w_in) # Aca se ejecuta el PE y se hacen los traslados
#                print("k[A_w_out,B_w_out,C_w_out] = ",[A_w_out,B_w_out,C_w_out])
                A_w[n-1-k][n-1-j] = A_w_out
                B_w[n-1-k][n-1-j] = B_w_out
                C_w[n-1-k][n-1-j] = C_w_out
                
#            print('A_w :\n',A_w)
#            print('B_w :\n',B_w)
        print('C_w :\n',C_w)
    file.close()

In [26]:
GSM(A1,B1)


 bucle del i =  0 

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
C_w :
 [[4 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 bucle del i =  1 

4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
C_w :
 [[7 8 0 0]
 [4 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 bucle del i =  2 

7 8 0 0 4 0 0 0 0 0 0 0 0 0 0 0
C_w :
 [[ 9 14 12  0]
 [ 7  8  0  0]
 [ 4  0  0  0]
 [ 0  0  0  0]]

 bucle del i =  3 

 9 14 12  0  7  8  0  0  4  0  0  0  0  0  0  0
C_w :
 [[10 18 21 16]
 [ 9 14 12  0]
 [ 7 12  0  0]
 [ 4  0  0  0]]

 bucle del i =  4 

10 18 21 16  9 14 12  0  7 12  0  0  4  0  0  0
C_w :
 [[10 20 27 28]
 [10 18 21 16]
 [ 9 21 12  0]
 [ 7 16  0  0]]

 bucle del i =  5 

10 20 27 28 10 18 21 16  9 21 12  0  7 16  0  0
C_w :
 [[10 20 30 36]
 [10 20 27 28]
 [10 27 21 16]
 [ 9 28 16  0]]

 bucle del i =  6 

10 20 30 36 10 20 27 28 10 27 21 16  9 28 16  0
C_w :
 [[10 20 30 40]
 [10 20 30 36]
 [10 30 27 28]
 [10 36 28 16]]

 bucle del i =  7 

10 20 30 40 10 20 30 36 10 30 27 28 10 36 28 16
C_w :
 [[10 20 30 40]
 [10 20 30 40]
 [10 30 30 36]
